name: Hello World Workflow (Dispatch with Env Variables)

# Trigger the workflow via github console and using variables inputs
on:
  push:
    branches:
      - main
      - features/**

jobs:
  hello-world-dev:
    runs-on: ubuntu-latest
    environment: dev # This corresponds to the DEV defined variables in Github Actions > Settings

    steps:
      - name: Print Hello, World!
        run: echo "Hello, World!"

      - name: Environment Name
        run: echo "You are running in ${{ vars.ENV_NAME }}!"

      - name: Sensitivity Level
        run: |
          echo "Your environment has ${{ vars.SENSITIVITY_LEVEL }} level"

  hello-world-uat:
    runs-on: ubuntu-latest
    environment: uat # This corresponds to the UAT defined variables in Github Actions > Settings

    steps:
      - name: Print Hello, World!
        run: echo "Hello, World!"

      - name: Environment Name
        run: echo "You are running in ${{ vars.ENV_NAME }}!"

      - name: Sensitivity Level
        run: |
          echo "Your environment has ${{ vars.SENSITIVITY_LEVEL }} level"
