name: Hello World Workflow (Push with variables)

# Edited file on 2 Sep 2024

# Trigger the workflow on push to the main branch and use github settings > secrets and variables
on:
  pull_request:
    branches:
      - main

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello, World!
        run: echo "Hello, World!"

      - name: Print Your Name
        run: echo "Hello, ${{ vars.NAME }}!" # Replace the name in Settings

      - name: Print Your Country
        run: echo "I'm from ${{ vars.COUNTRY }}" # Replace the country in Settings

      - name: Print Multiple Lines
        run: |
          echo "Exiting..."
          echo "Ending session..."
